GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
  "title": "Hello World",
  "author": "Jesse Gill",
  "url": "http://hello-world"

}

###
DELETE http://localhost:3003/api/blogs/6411b402c3b4997c134a7364

###
PUT http://localhost:3003/api/blogs/6411aba1246b2013c167a151
Content-Type: application/json

{
  "title": "The Alchemist",
  "author": "Paulo Coelho",
  "url": "https://www.adlibris.com/fi/kirja/the-alchemist-25th-anniversary-edition-9780062355300?gclid=CjwKCAiAmJGgBhAZEiwA1JZolg1JEgl8Fe8Av2KnWu01T3qiwQbpe-hUJmiJLOU55Zr4F7AV8eTT1xoCf6cQAvD_BwE",
  "likes": 100,
  "id": "6411aba1246b2013c167a151"
}
###
PUT http://localhost:3003/api/blogs/6411b0246fb75c737588c89a
Content-Type: application/json

{
    "likes": 100
}

###
post http://localhost:3003/api/users
Content-Type: application/json

{
  "name" : "Maytor",
  "username" : "wh",
  "password" : "milk&sugar"
}